hostname router1
log syslog
no ipv6 forwarding
!
ip route 177.91.248.0/24 Null0
ip route 177.91.249.0/24 Null0
ip route 177.91.250.0/24 Null0
ip route 177.91.251.0/24 Null0
ip route 177.91.252.0/24 Null0
ip route 177.91.253.0/24 Null0
ip route 177.91.254.0/24 Null0
ip route 177.91.255.0/24 Null0
!
interface eth1
 ip address 192.168.12.1/30
exit
!
router bgp 263224
 neighbor 192.168.12.2 remote-as 3356
 neighbor 192.168.12.2 description Cirion
 !
 address-family ipv4 unicast
  network 177.91.248.0/24
  network 177.91.249.0/24
  network 177.91.250.0/24
  network 177.91.251.0/24
  network 177.91.252.0/24
  network 177.91.253.0/24
  network 177.91.254.0/24
  network 177.91.255.0/24
  neighbor 192.168.12.2 soft-reconfiguration inbound
  neighbor 192.168.12.2 route-map TODO-IPv4-IN in
  neighbor 192.168.12.2 route-map TODO-IPv4-OUT out
 exit-address-family
exit
!
ip prefix-list PERMIT-ALL-IPv4 seq 5 permit any
!
route-map TODO-IPv4-IN permit 10
 match ip address prefix-list PERMIT-ALL-IPv4
exit
!
route-map TODO-IPv4-OUT permit 10
 match ip address prefix-list PERMIT-ALL-IPv4
exit
!
